apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-deploy.yaml

configMapGenerator:
  - name: frontend-codigo
    files:
      - codigo-web/index.html
      - codigo-web/style.css
      - codigo-web/script.js
      - codigo-web/registro.html
      - codigo-web/profesor.html