apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - capa-datos/mysql-ICA.yaml
  - capa-logica/codigo-backend.yaml
  - capa-logica/deploy-backend.yaml
  - capa-presentacion/