apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pdf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: fastapi
        image: python:3.9-alpine
        workingDir: /app
        command: ["/bin/sh", "-c", "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 80"]
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mysql-nodeport"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "300m"
        volumeMounts:
        - name: codigo-vol
          mountPath: /app/main.py
          subPath: main.py
        - name: codigo-vol
          mountPath: /app/requirements.txt
          subPath: requirements.txt
        # NUEVO: Montaje del disco duro para los PDFs
        - name: pdf-storage
          mountPath: /app/pdfs
      volumes:
      - name: codigo-vol
        configMap:
          name: backend-codigo
      - name: pdf-storage
        persistentVolumeClaim:
          claimName: backend-pdf-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
spec:
  type: NodePort
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30090